# -*- coding: utf-8 -*-
"""Foldndeploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScqOlLakOBRHaOhnOJgd8Gay62QJ8nZl
"""

pip install gradio   #can use for graphical user interface

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

!pip install ensemble_boxes

import glob
import pandas as pd
import numpy as np
import os
import yaml
import shutil
from pathlib import Path
from sklearn.model_selection import KFold,StratifiedKFold
from ultralytics import YOLO
import torch
from ensemble_boxes import weighted_boxes_fusion
import cv2

## Load test images

# Get all jpg files in CRISPR folder
dir_path = "/content/drive/MyDrive/Folds/k-fold/Test_horizontal"
search_pattern_jpg = os.path.join(dir_path, "**", "*.jpg")

# Use glob with recursive=True
jpg_files = glob.glob(search_pattern_jpg, recursive=True)
jpg_files.sort()

import gradio as gr
import PIL.Image as Image
import numpy as np
import cv2
from ultralytics import YOLO
from ensemble_boxes import weighted_boxes_fusion

# =======================================================
#                 Configuration
# =======================================================
MODEL_PATHS = [
    "/content/drive/MyDrive/Folds/k-fold/best/best.pt",
    "/content/drive/MyDrive/Folds/k-fold/best/best (1).pt",
    "/content/drive/MyDrive/Folds/k-fold/best/best (2).pt",
    "/content/drive/MyDrive/Folds/k-fold/best/best (3).pt",
    "/content/drive/MyDrive/Folds/k-fold/best/best (4).pt"
]
CLASS_NAMES = {0: "Negative", 1: "Positive"}
COLORS = [(0, 255, 0), (255, 0, 0)]  # Green=Negative, Red=Positive

# Load ensemble models once
models = [YOLO(p, task="detect") for p in MODEL_PATHS]


# =======================================================
#        Post-fusion NMS: keep highest score only
# =======================================================
def iou_xyxy(a, b):
    # a, b are [x1,y1,x2,y2] in pixels
    xA = max(a[0], b[0])
    yA = max(a[1], b[1])
    xB = min(a[2], b[2])
    yB = min(a[3], b[3])

    inter_w = max(0, xB - xA)
    inter_h = max(0, yB - yA)
    inter = inter_w * inter_h

    area_a = max(0, a[2] - a[0]) * max(0, a[3] - a[1])
    area_b = max(0, b[2] - b[0]) * max(0, b[3] - b[1])

    union = area_a + area_b - inter + 1e-9
    return inter / union


def nms_keep_highest(boxes, scores, labels, iou_thr=0.5):
    """
    Class-agnostic NMS: for overlapping boxes, keep only the highest score.
    boxes:  list of [x1,y1,x2,y2] (pixels)
    scores: list of floats
    labels: list of ints
    """
    if len(boxes) == 0:
        return [], [], []

    order = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)
    keep = []

    while order:
        best = order.pop(0)
        keep.append(best)

        remaining = []
        for j in order:
            if iou_xyxy(boxes[best], boxes[j]) <= iou_thr:
                remaining.append(j)
        order = remaining

    boxes_kept = [boxes[i] for i in keep]
    scores_kept = [scores[i] for i in keep]
    labels_kept = [labels[i] for i in keep]
    return boxes_kept, scores_kept, labels_kept


# =======================================================
#                 Image helpers
# =======================================================
def extract_channel(img_np, channels):
    """Extract specified color channels (list) with black background. img_np is RGB."""
    filtered = np.zeros_like(img_np)
    rgb_channel_idx_map = {"red": 0, "green": 1, "blue": 2}
    for ch in channels:
        idx = rgb_channel_idx_map[ch]
        filtered[:, :, idx] = img_np[:, :, idx]
    return filtered


def calculate_rlu(img_np, boxes, channels):
    """Calculate RFU inside circular droplet masks for given color channels."""
    rlu_values = []
    annotated_img = img_np.copy()

    rgb_channel_idx_map = {"red": 0, "green": 1, "blue": 2}
    idxs = [rgb_channel_idx_map[ch] for ch in channels]

    for box in boxes:
        x1, y1, x2, y2 = map(int, box)
        cropped = img_np[y1:y2, x1:x2].copy()

        h, w = cropped.shape[:2]
        if h <= 1 or w <= 1:
            rlu_values.append("0.00e+00")
            continue

        mask = np.zeros((h, w), dtype=np.uint8)
        center = (w // 2, h // 2)
        radius = max(1, min(w, h) // 2)
        cv2.circle(mask, center, radius, 1, -1)

        intensity_sum = np.sum(cropped[:, :, idxs], axis=2)
        rlu = float(np.sum(intensity_sum * mask))
        rlu_str = f"{rlu:.2e}"
        rlu_values.append(rlu_str)

        overlay_color = (255, 255, 0)  # cyan-ish overlay
        cv2.circle(annotated_img, (x1 + center[0], y1 + center[1]), radius, overlay_color, 2)
        cv2.putText(
            annotated_img,
            f"RFU: {rlu_str}",
            (x1, max(30, y1 - 10)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )

    return annotated_img, rlu_values


# =======================================================
#                 Main prediction
# =======================================================
def predict_image(img, conf_threshold, iou_threshold):
    """Ensemble YOLO detection + RFU measurement (keep only best box per object)."""
    img_np = np.array(img)  # RGB
    h, w, _ = img_np.shape

    boxes_list = []
    scores_list = []
    labels_list = []

    # --- 1) Predictions from each model ---
    for model in models:
        results = model.predict(
            source=img,
            conf=conf_threshold,
            iou=iou_threshold,
            imgsz=640,
            verbose=False,
            agnostic_nms=False
        )[0]

        if len(results.boxes) > 0:
            boxes_list.append(results.boxes.xyxyn.cpu().numpy().tolist())  # normalized
            scores_list.append(results.boxes.conf.cpu().numpy().tolist())
            labels_list.append(results.boxes.cls.cpu().numpy().astype(int).tolist())
        else:
            boxes_list.append([])
            scores_list.append([])
            labels_list.append([])

    # --- 2) Weighted Boxes Fusion ---
    fused_boxes, fused_scores, fused_labels = weighted_boxes_fusion(
        boxes_list,
        scores_list,
        labels_list,
        weights=[1] * len(MODEL_PATHS),
        iou_thr=iou_threshold,
        skip_box_thr=conf_threshold
    )

    # Convert fused boxes to pixel coords
    fused_boxes_xyxy_pixel = []
    for b in fused_boxes:
        x1, y1, x2, y2 = (b[0] * w, b[1] * h, b[2] * w, b[3] * h)
        fused_boxes_xyxy_pixel.append([x1, y1, x2, y2])

    # --- 3) Post-fusion NMS: keep only highest probability per object ---
    fused_boxes_xyxy_pixel, fused_scores, fused_labels = nms_keep_highest(
        fused_boxes_xyxy_pixel,
        list(fused_scores),
        list(fused_labels),
        iou_thr=iou_threshold
    )

    # --- 4) Prepare channel images ---
    red_green_img_np = extract_channel(img_np, ["red", "green"])
    blue_img_np = extract_channel(img_np, ["blue"])

    annotated_red_green_display = red_green_img_np.copy()
    annotated_blue_display = blue_img_np.copy()
    yolo_annotated_display = img_np.copy()

    combined_rlu_values_str_list = []
    blue_rlu_values_str_list = []

    if len(fused_boxes_xyxy_pixel) > 0:
        mask_overlay = np.zeros_like(yolo_annotated_display, dtype=np.uint8)
        alpha = 0.3

        for box, score, label in zip(fused_boxes_xyxy_pixel, fused_scores, fused_labels):
            x1, y1, x2, y2 = map(int, box)

            label_int = int(label)
            label_text = f"{CLASS_NAMES.get(label_int, str(label_int))} {float(score):.2f}"
            color = COLORS[label_int] if label_int < len(COLORS) else (0, 0, 0)

            # Draw bounding box + label
            cv2.rectangle(yolo_annotated_display, (x1, y1), (x2, y2), color, 2)
            cv2.putText(
                yolo_annotated_display,
                label_text,
                (x1, max(20, y1 - 10)),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.9,
                color,
                2
            )

            # Circular filled overlay
            center = ((x1 + x2) // 2, (y1 + y2) // 2)
            radius = max(1, int(min(x2 - x1, y2 - y1) // 2))
            cv2.circle(mask_overlay, center, radius, color, -1)

            # RFU per box
            _, current_combined = calculate_rlu(red_green_img_np, [box], ["red", "green"])
            _, current_blue = calculate_rlu(blue_img_np, [box], ["blue"])
            combined_rlu_values_str_list.extend(current_combined)
            blue_rlu_values_str_list.extend(current_blue)

        # Blend overlay
        yolo_annotated_display = cv2.addWeighted(yolo_annotated_display, 1, mask_overlay, alpha, 0)

        # RFU overlays on channel images
        annotated_red_green_display, _ = calculate_rlu(red_green_img_np, fused_boxes_xyxy_pixel, ["red", "green"])
        annotated_blue_display, _ = calculate_rlu(blue_img_np, fused_boxes_xyxy_pixel, ["blue"])

        combined_rlu_output = (
            f"Detected {len(fused_boxes_xyxy_pixel)} droplets. RFU: {', '.join(combined_rlu_values_str_list)}"
        )
        blue_rlu_output = (
            f"Detected {len(fused_boxes_xyxy_pixel)} droplets. RFU: {', '.join(blue_rlu_values_str_list)}"
        )
    else:
        combined_rlu_output = "No droplets detected"
        blue_rlu_output = "No droplets detected"

    return (
        Image.fromarray(yolo_annotated_display),
        combined_rlu_output,
        blue_rlu_output,
        Image.fromarray(annotated_red_green_display),
        Image.fromarray(annotated_blue_display),
    )


# =======================================================
#                 Gradio Interface
# =======================================================
iface = gr.Interface(
    fn=predict_image,
    inputs=[
        gr.Image(type="pil", label="Upload Image"),
        gr.Slider(minimum=0, maximum=1, value=0.80, label="Confidence threshold"),
        gr.Slider(minimum=0, maximum=1, value=0.80, label="IoU threshold"),
    ],
    outputs=[
        gr.Image(type="pil", label="YOLO Detection Result"),
        gr.Textbox(label="Red + Green Channel RFU (scientific notation)"),
        gr.Textbox(label="Blue Channel RFU (scientific notation)"),
        gr.Image(type="pil", label="Red + Green Channel with RFU Overlay"),
        gr.Image(type="pil", label="Blue Channel with RFU Overlay"),
    ],
    title="Fluorescence RFU Detection (Red+Green vs Blue) with Ensemble Model",
    description="Detect droplets using an ensemble of YOLO models and calculate RFU for combined red+green fluorescence and blue fluorescence channels.",
)

if __name__ == "__main__":
    iface.launch(share=True)