# -*- coding: utf-8 -*-
"""Fold5n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWgMi6B1uG_FHl0JgdZnV1huCbH1cZ__
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile, shutil
from pathlib import Path

TRAIN_ZIP = "/content/drive/MyDrive/Folds/Folds/fold5/fold_5_train (1).zip"
VAL_ZIP   = "/content/drive/MyDrive/Folds/Folds/fold5/fold_5_val (1).zip"

fold_root = Path("/content/fold_5")

# clean old extracted folder only (safe)
if fold_root.exists():
    shutil.rmtree(fold_root)

(fold_root/"train").mkdir(parents=True, exist_ok=True)
(fold_root/"val").mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(TRAIN_ZIP, "r") as z:
    z.extractall(fold_root/"train")

with zipfile.ZipFile(VAL_ZIP, "r") as z:
    z.extractall(fold_root/"val")

print("Unzipped to:", fold_root)
print("Train images:", len(list((fold_root/"train/images").glob("*"))))
print("Val images  :", len(list((fold_root/"val/images").glob("*"))))
print("Train labels:", len(list((fold_root/"train/labels").glob("*.txt"))))
print("Val labels  :", len(list((fold_root/"val/labels").glob("*.txt"))))

import yaml
from pathlib import Path

data = {
    "path": "/content/fold_5",
    "train": "train/images",
    "val": "val/images",
    "names": {
        0: "Negative",
        1: "Positive"
    }
}

yaml_path = Path("/content/fold_5_data.yaml")
yaml_path.write_text(yaml.dump(data, sort_keys=False))
print("Saved:", yaml_path)
print(yaml_path.read_text())

!pip install -q ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %pip install "ultralytics<=8.3.40" supervision roboflow

!yolo task=segment mode=train \
  model=yolo11s-seg.pt \
  data=/content/fold_5_data.yaml \
  epochs=100 \
  imgsz=640 \
  batch=16 \
  hsv_h=0.04 \
  hsv_s=0.25 \
  hsv_v=0.15 \
  shear=0.0 \
  fliplr=0.5 \
  flipud=0.0 \
  agnostic_nms=True \
  plots=True

from ultralytics import YOLO

model = YOLO("/content/runs/segment/train2/weights/best.pt")

metrics = model.val(
    data="/content/fold_5_data.yaml",
    split="train",          # This evaluates train set
    conf=0.25,
    iou=0.45,
    agnostic_nms=True,
    plots=True
)

from IPython.display import Image as IPyImage
IPyImage(filename=f'/content/runs/segment/val3/confusion_matrix.png', width=600)

from ultralytics import YOLO

model = YOLO("/content/runs/segment/train2/weights/best.pt")

metrics = model.val(
    data="/content/fold_5_data.yaml",
    split="val",          # This evaluates valid set
    conf=0.25,
    iou=0.45,
    agnostic_nms=True,
    plots=True
)

IPyImage(filename=f'/content/runs/segment/val4/confusion_matrix.png', width=600)

model = YOLO("/content/runs/segment/train2/weights/best.pt")

Results = model.predict(
    source="/content/fold_5/val/images",
    conf=0.25,
    iou=0.45,
    agnostic_nms=True,
    plots=True,
    save=True,
    save_txt=True
)

import os
from IPython.display import Image, display

pred_dir = "/content/runs/segment/predict2"

files = [f for f in os.listdir(pred_dir) if f.endswith(".jpg") or f.endswith(".png")]

for f in files[:]:
    display(Image(filename=os.path.join(pred_dir, f)))

IPyImage(filename=f'/content/runs/segment/train2/results.png', width=600)

import pandas as pd
import os

label_dir = "/content/runs/segment/predict2/labels"

rows = []

for file in os.listdir(label_dir):
    path = os.path.join(label_dir, file)
    if os.path.getsize(path) == 0:
        rows.append([file, "no_detection"])
    else:
        with open(path) as f:
            lines = f.readlines()
            for line in lines:
                cls = line.split()[0]
                conf = line.split()[1]
                rows.append([file, cls, conf])

df = pd.DataFrame(rows, columns=["image", "class", "confidence"])
df.head()

import os
from zipfile import ZipFile


folder_path = "/content/runs"
zip_file = "/content/runs.zip"


with ZipFile(zip_file, 'w') as zipf:
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            file_path = os.path.join(root, file)
            zipf.write(file_path, os.path.relpath(file_path, folder_path))

from google.colab import files

# Download the zip file
files.download(zip_file)